import Head from 'next/head';
import { styled } from '@mui/material/styles';
import { useState } from 'react';
import Header from '../components/Header/Header';
import { Wordle } from '../components/Wordle';
import { useLocalStorage } from '../hooks/useLocalStorage';
import {
  gameStateInitial,
  statisticsStateInitial,
} from '../lib/initialGameAndStatisticsState';

const PageStyles = styled('div')(() => ({
  minHeight: '100vh',
  display: 'flex',
  flexDirection: 'column',
  backgroundColor: 'var(--color-background)',
}));

const InnerStyles = styled('main')(() => ({
  maxWidth: '1000px',
  margin: '1rem auto',
  flex: 1,
  display: 'flex',
  flexDirection: 'column',
}));

export default function Index() {
  const [gameState, setGameState] = useLocalStorage(
    'gameState',
    gameStateInitial
  );
  const [statisticsState, setStatisticsState] = useLocalStorage(
    'statisticsState',
    statisticsStateInitial
  );
  const [infoMsg, setInfoMsg] = useState('');
  const [countInfoMsgs, setCountInfoMsgs] = useState(0);
  const [openStatistics, setOpenStatistics] = useState(false);

  return (
    <>
      <Head>
        <title>Wordle Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageStyles>
        <Header
          gameState={gameState}
          setInfoMsg={setInfoMsg}
          setCountInfoMsgs={setCountInfoMsgs}
          statisticsState={statisticsState}
          openStatistics={openStatistics}
          setOpenStatistics={setOpenStatistics}
        />
        <InnerStyles>
          <Wordle
            gameState={gameState}
            setGameState={setGameState}
            infoMsg={infoMsg}
            setInfoMsg={setInfoMsg}
            countInfoMsgs={countInfoMsgs}
            setCountInfoMsgs={setCountInfoMsgs}
            setStatisticsState={setStatisticsState}
            setOpenStatistics={setOpenStatistics}
          />
        </InnerStyles>
      </PageStyles>
    </>
  );
}
