import Head from 'next/head';
import { Wordle } from '../components/Wordle';

export default function Home() {
  return (
    <>
      <Head>
        <title>Wordle Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wordle />
    </>
  );
}
