# fetch random number at 10am UTC (midnight UTC +14)
name: Daily random number fetch
on:
  schedule:
    # - cron: '0 10 * * *'
    - cron: '56 13 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API route
        run: |
          curl --request POST \
          --url 'https://wordle-clone-next-js.vercel.app/api/random-nums-set' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_FETCH_RANDOM_NUM }}'